### ISSUE TITLE
Application crash when registering a name already registered.

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#101]
When users receive an invitation and tries to introduce their names, if there is someone already with the same name in the DB the application crashes.

**URL:**
[https://managing-registers-staging.cloudapps.digital/users/invitation/accept](https://managing-registers-staging.cloudapps.digital/users/invitation/accept)

**Steps to recreate:**
1. Login as a custodian user
2. Click 'Manage team'
3. Click 'Invite team member'
4. Enter an email address
5. Choose 'Advanced' form the permissions radio group
6. Click the 'Send invite' button
7. Log out
8. Accept invitation
9. Introduce 'Full name' (ex: John Doe) and credentials.
10. Click 'Set my password' button
11. Log out
12. Repeat steps 1 to 10 with a different email but the same name (ex: John Doe)

**Expected result:**
The user should be able to register even there is another user with the same name.

**Actual result:**
Application crashes throwing a `UniqueViolation` exception

**Comment by elliecraven** [comment]
needed before we ship
