### ISSUE TITLE
Register assignation to custodian when invitation is sent

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#115]
When an admin tries to send an invitation to a custodian and assign a register, if the register has already a custodian or it's part of an invitation already sent, it doesn't show in the dropdown list but it can be typed. Once the invitation is sent, the custodian can accept the invitation but he/she is not going to have a register assigned.

Considering the 'Delete invitation' functionality does not exist, this can produce blocking situation difficult to unblock just using the RMT.

**URL:**
https://managing-registers-staging.cloudapps.digital/users/invitation/new?role=custodian

**Steps to recreate:**
1. Login as an admin
2. Click 'Manage custodians'
3. Invite a new custodian and use a already assigned Register.

**Expected result:**
a) A message that the register can not be assigned to the custodian because is already assigned
b) Restrict the text can be typed in the dropdown list to just the available options.
Note: Business should decided about this.

**Actual result:**
Invitation is sent as usual and can be accepted, leaving a custodian without Register

/cc @Maidment64

**Comment by elliecraven** [comment]
Option a) 'A message that the register cannot be assigned...' please!

**Comment by fjavierm** [comment]
Does not apply any more. It is not possible to assign already assigned registers any more
