### ISSUE TITLE
Displaying registers order by name

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#132]
Name is not a mandatory field in all the Registers then, when we are trying to display a Register's content if one or more of the records has an empty (null) name, the application is going to crash.

The default sort order for Registers should be by 'key'.

Note for developers: RegisterController line 13.

/cc @Maidment64

**Comment by fjavierm** [comment]
@Maidment64 I have created it myself

**Comment by elliecraven** [comment]
in /records, the records are displayed with the most recently changed at the top (by entry number). 

If no records have changed, or after the ones which have recently changed, they should be sorted alphabetically by key.
