### ISSUE TITLE
Custodian's table has repeated rows

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#155]
When an admin goes to the 'Manage Custodians' page, the table listing the custodian shows repeated rows.

If one of the custodians is in more than one time, the same row is repeated as many times as teams has the custodian. It makes sense to have the custodian repeated but the values 'Registers' and the links to 'View Team' should be different for each row, right now, their are the same for all the entries related with a custodian.

**URL**
/custodians#custodians

** Steps to reproduce**
1. Log as admin
2. Click 'Manage Custodians'

**Expected result**
If a custodian is in more than one team, a row for each team the custodian is in but with different registers and links.

**Actual Result**
All the rows are exactly the same.

/cc @Maidment64

**Comment by elliecraven** [comment]
not 100% sure I understand - can I clarify that: 

currently if a custodian is assigned to more than one register, they appear multiple times in the 'manage custodians' table

this should be the case, but each row should relate to a different register - currently each row for an individual repeats the same register. 

so currently:

Ellie Craven -- > Register Register
Ellie Craven -- > Register Register

should be

Ellie Craven -- > Register Register
Ellie Craven -- > Field Register

If this is the case - are we confident that this is an error in the display of the assigned register, and not an error in the staging app created by members of the team being added to the same register more than once before we had implemented any validation? 

Either way, we should fix this before external release 1.
