### ISSUE TITLE
Country Key validation.

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#191]
Despite there is a message saying `The country's 2-letter ISO 3166-2 alpha2 code.` the country field accepts any length.

**Expected result**
The value should be rejected

**Actual result**
The value is accepted

/cc @Maidment64

**Comment by gidsg** [comment]
For me this is a wontfix. This is just a free text description. I think we should only do validation derived from the datatype register.

**Comment by elliecraven** [comment]
This one is a bit tricky imo - for country I suppose we could validate that the value entered is two alpha characters on client side, but this would be custom for each register and isn't something contained in metadata, so would need hardcoding in somewhere. Most of the other registers have more exceptions in their ID structure - they could be different lengths or content. 

This feels like a thread that's too tricky to pull at the moment, but we should see how it goes in release and revisit if it presents an issue to custodians using the tool.

**Comment by arnau** [comment]
I agree, the business domain for a register is not generic enough to have generic validation rules at this level. And I don't think we are in a position to consider more sophisticated approaches like custom rule definition per register.
