### ISSUE TITLE
Account management journeys

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#54]
Account management all on one screen in the manage registers app. The design indicates one thing per page.

**URL:**
https://managing-registers-staging.cloudapps.digital/users/19

**Steps to recreate:**

1. Log in
2. Click the user name in the header

**Expected result:**

![screen shot 2017-10-16 at 17 55 42](https://user-images.githubusercontent.com/27765242/31624710-7e0d8490-b29b-11e7-94d0-3e4e2c4b2574.png)

![screen shot 2017-10-16 at 17 59 36](https://user-images.githubusercontent.com/27765242/31624820-d8bf8c80-b29b-11e7-8ba2-323d4b25efdb.png)

**Actual result:**

![screen shot 2017-10-16 at 17 28 40](https://user-images.githubusercontent.com/27765242/31624724-851c69c2-b29b-11e7-964b-8651da8a5f63.png)

![screen shot 2017-10-16 at 17 59 51](https://user-images.githubusercontent.com/27765242/31624824-de3f14f0-b29b-11e7-9118-9b080c866fd6.png)

**Comment by elliecraven** [comment]
not required for this release - next iteration

**Comment by arnau** [comment]
Will reopen this one when we get more clarity on accounts.
