### ISSUE TITLE
'Pending invites' tab and search box not showing on 'Manage custodians' page 

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#56]
The 'Pending invites' tab and the search box is not showing. The test confirmed that the 'Pending invites' tab also does not show when an invite has been sent but not accepted.

**URL:**

https://managing-registers-staging.cloudapps.digital/custodians

**Steps to recreate:**

1. Login as an admin
2. Click 'Manage custodians'
3. Invite a new custodian
4. Click 'Manage custodians'

**Expected result:**

https://projects.invisionapp.com/d/main#/console/10972863/233584225/preview

**Actual result:**

![screen shot 2017-10-16 at 18 02 28](https://user-images.githubusercontent.com/27765242/31625754-1ffd5c1e-b29f-11e7-8c32-faecbfc1c0b4.png)

**Comment by elliecraven** [comment]
required for this version - will make it much easier for us to release
