### ISSUE TITLE
Do not allow admin users to remove all the register inputs

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#59]
When adding a new custodian an admin user can remove all 'Register' inputs on the invite custodian form. The form should always display at least one 'Register' input. When only one 'Register' input is showing, the 'Remove register' link should not show.

**URL:**

https://managing-registers-staging.cloudapps.digital/users/invitation/new?role=custodian

**Steps to recreate:**

1. Log in as an admin
2. Click on 'Manage custodians'
3. Click on the 'Invite custodian' button
4. Click on the 'Remove register' link
5. If you submit the form, the app fails

**Expected result:**

https://projects.invisionapp.com/d/main#/console/10972863/233584220/preview

**Actual result:**

![screen shot 2017-10-16 at 18 39 09](https://user-images.githubusercontent.com/27765242/31626374-5bafa2ce-b2a1-11e7-8402-ce13231b0dda.png)

![screen shot 2017-10-16 at 18 39 20](https://user-images.githubusercontent.com/27765242/31626379-5f605562-b2a1-11e7-9421-62f025d20410.png)

**Comment by fjavierm** [comment]
I guess some controls can be added in the BE to return an error when an invite is sent without registers, but I think the FE should add some behaviour to disable the link `Remove register` if there is just one box. Never leave the user to go down to zero registers. What do you think @danmitchell-?

**Comment by danmitchell-** [comment]
I'm looking at seeing if we can hide the remove link when there is only one input
