### ISSUE TITLE
Custodian cannot invite team member with advanced permissions

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#66]
If you're logged in with an account with custodian permissions, and then invite a new team member with advanced permissions, the invite form does not submit. The error messages suggest that it has validated against name and password, neither input is available on the form.

**URL:**

https://managing-registers-staging.cloudapps.digital/users/invitation

**Steps to recreate:**

1. Login as a custodian user
2. Click 'Manage team'
3. Click 'Invite team member'
4. Enter an email address
5. Choose 'Advanced' form the permissions radio group
6. Click the 'Send invite' button

**Expected result:**

The form submits and the user is taken back to the 'Manage team' page with a confirmation alert. The invited user is visible in the 'Pending invites' section at the bottom of the page.
https://projects.invisionapp.com/d/main#/console/10972863/233583091/preview

**Actual result:**

![screen shot 2017-10-17 at 12 00 18](https://user-images.githubusercontent.com/27765242/31661729-a8e987c0-b333-11e7-84de-acc42981cbcb.png)

**Comment by fjavierm** [comment]
I cannot reproduce it locally. Any idea @danmitchell-? Do we need to deploy in staging and it's something that it has been already fixed? Or, Have we fix something that it has solved this as a 'collateral damage'? Do we need to deploy changes to staging time to time?

**Comment by fjavierm** [comment]
Basic is not working either

**Comment by elliecraven** [comment]
fix required before we ship this iteration
