### ISSUE TITLE
App error when trying to reject a register update

### ISSUE THREAD

**Issue by bentateart** [openregister/managing-registers#83]
As a custodian reviewing a basic user's update, I can review the update, but when I reject it then app fails.

**Steps to recreate:**

1. Log in as a custodian
2. Go the Country register
3. Click on the 'Updates for review' tab
4. Click 'Review'
5. Select 'Decline updates' from the radio options
6. Click the 'Continue' button
7. Enter some text in the 'details' text box
8. Click the 'Submit' button

**Error message:**

![screen shot 2017-10-18 at 15 04 49](https://user-images.githubusercontent.com/27765242/31723592-d486ec16-b40e-11e7-8b3b-fb262f1530d9.png)

**Comment by elliecraven** [comment]
needed before we ship

**Comment by gidsg** [comment]
This works locally but 500s on staging. I am taking a look now.
